/* eslint-disable */

export const tala = [[{
  "headWord":"tala",
  "binId":424804,
  "wordClass":"so",
  "section":"alm",
  "forms":[
    {
       "form":"tala",
       "grammarTag":"GM-FH-NT-1P-ET",
       "tags":{
          "person":"1P",
          "number":"ET",
          "tense":"NT",
          "voice":"GM",
          "mood":"FH"
       }
    },
    {
       "form":"talaði",
       "grammarTag":"GM-FH-ÞT-1P-ET",
       "tags":{
          "person":"1P",
          "number":"ET",
          "tense":"ÞT",
          "voice":"GM",
          "mood":"FH"
       }
    },
    {
       "form":"tali",
       "grammarTag":"GM-VH-NT-1P-ET",
       "tags":{
          "person":"1P",
          "number":"ET",
          "tense":"NT",
          "voice":"GM",
          "mood":"VH"
       }
    },
    {
       "form":"talaði",
       "grammarTag":"GM-VH-ÞT-1P-ET",
       "tags":{
          "person":"1P",
          "number":"ET",
          "tense":"ÞT",
          "voice":"GM",
          "mood":"VH"
       }
    },
    {
       "form":"talast",
       "grammarTag":"MM-FH-NT-1P-ET",
       "tags":{
          "person":"1P",
          "number":"ET",
          "tense":"NT",
          "voice":"MM",
          "mood":"FH"
       }
    },
    {
       "form":"talaðist",
       "grammarTag":"MM-FH-ÞT-1P-ET",
       "tags":{
          "person":"1P",
          "number":"ET",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"FH"
       }
    },
    {
       "form":"talist",
       "grammarTag":"MM-VH-NT-1P-ET",
       "tags":{
          "person":"1P",
          "number":"ET",
          "tense":"NT",
          "voice":"MM",
          "mood":"VH"
       }
    },
    {
       "form":"talaðist",
       "grammarTag":"MM-VH-ÞT-1P-ET",
       "tags":{
          "person":"1P",
          "number":"ET",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"VH"
       }
    },
    {
       "form":"talaðu",
       "grammarTag":"GM-BH-ET",
       "tags":{
          "number":"ET",
          "voice":"GM"
       }
    },
    {
       "form":"talaður",
       "grammarTag":"LHÞT-SB-KK-NFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"KK"
       }
    },
    {
       "form":"talaðan",
       "grammarTag":"LHÞT-SB-KK-ÞFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"KK"
       }
    },
    {
       "form":"töluðum",
       "grammarTag":"LHÞT-SB-KK-ÞGFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"KK"
       }
    },
    {
       "form":"talaðs",
       "grammarTag":"LHÞT-SB-KK-EFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"KK"
       }
    },
    {
       "form":"töluð",
       "grammarTag":"LHÞT-SB-KVK-NFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"KVK"
       }
    },
    {
       "form":"talaða",
       "grammarTag":"LHÞT-SB-KVK-ÞFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"KVK"
       }
    },
    {
       "form":"talaðri",
       "grammarTag":"LHÞT-SB-KVK-ÞGFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"KVK"
       }
    },
    {
       "form":"talaðrar",
       "grammarTag":"LHÞT-SB-KVK-EFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"KVK"
       }
    },
    {
       "form":"talað",
       "grammarTag":"LHÞT-SB-HK-NFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"HK"
       }
    },
    {
       "form":"talað",
       "grammarTag":"LHÞT-SB-HK-ÞFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"HK"
       }
    },
    {
       "form":"töluðu",
       "grammarTag":"LHÞT-SB-HK-ÞGFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"HK"
       }
    },
    {
       "form":"talaðs",
       "grammarTag":"LHÞT-SB-HK-EFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"HK"
       }
    },
    {
       "form":"talaði",
       "grammarTag":"LHÞT-VB-KK-NFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"KK"
       }
    },
    {
       "form":"talaða",
       "grammarTag":"LHÞT-VB-KK-ÞFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"KK"
       }
    },
    {
       "form":"talaða",
       "grammarTag":"LHÞT-VB-KK-ÞGFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"KK"
       }
    },
    {
       "form":"talaða",
       "grammarTag":"LHÞT-VB-KK-EFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"KK"
       }
    },
    {
       "form":"talaða",
       "grammarTag":"LHÞT-VB-KVK-NFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"KVK"
       }
    },
    {
       "form":"töluðu",
       "grammarTag":"LHÞT-VB-KVK-ÞFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"KVK"
       }
    },
    {
       "form":"töluðu",
       "grammarTag":"LHÞT-VB-KVK-ÞGFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"KVK"
       }
    },
    {
       "form":"töluðu",
       "grammarTag":"LHÞT-VB-KVK-EFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"KVK"
       }
    },
    {
       "form":"talaða",
       "grammarTag":"LHÞT-VB-HK-NFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"HK"
       }
    },
    {
       "form":"talaða",
       "grammarTag":"LHÞT-VB-HK-ÞFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"HK"
       }
    },
    {
       "form":"talaða",
       "grammarTag":"LHÞT-VB-HK-ÞGFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"HK"
       }
    },
    {
       "form":"talaða",
       "grammarTag":"LHÞT-VB-HK-EFET",
       "tags":{
          "number":"ET",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"HK"
       }
    },
    {
       "form":"talast",
       "grammarTag":"OP-MM-FH-NT-1P-ET",
       "tags":{
          "person":"1P",
          "number":"ET",
          "tense":"NT",
          "voice":"MM",
          "mood":"FH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talaðist",
       "grammarTag":"OP-MM-FH-ÞT-1P-ET",
       "tags":{
          "person":"1P",
          "number":"ET",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"FH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talist",
       "grammarTag":"OP-MM-VH-NT-1P-ET",
       "tags":{
          "person":"1P",
          "number":"ET",
          "tense":"NT",
          "voice":"MM",
          "mood":"VH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talaðist",
       "grammarTag":"OP-MM-VH-ÞT-1P-ET",
       "tags":{
          "person":"1P",
          "number":"ET",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"VH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talar",
       "grammarTag":"GM-FH-NT-2P-ET",
       "tags":{
          "person":"2P",
          "number":"ET",
          "tense":"NT",
          "voice":"GM",
          "mood":"FH"
       }
    },
    {
       "form":"talaðir",
       "grammarTag":"GM-FH-ÞT-2P-ET",
       "tags":{
          "person":"2P",
          "number":"ET",
          "tense":"ÞT",
          "voice":"GM",
          "mood":"FH"
       }
    },
    {
       "form":"talir",
       "grammarTag":"GM-VH-NT-2P-ET",
       "tags":{
          "person":"2P",
          "number":"ET",
          "tense":"NT",
          "voice":"GM",
          "mood":"VH"
       }
    },
    {
       "form":"talaðir",
       "grammarTag":"GM-VH-ÞT-2P-ET",
       "tags":{
          "person":"2P",
          "number":"ET",
          "tense":"ÞT",
          "voice":"GM",
          "mood":"VH"
       }
    },
    {
       "form":"talast",
       "grammarTag":"MM-FH-NT-2P-ET",
       "tags":{
          "person":"2P",
          "number":"ET",
          "tense":"NT",
          "voice":"MM",
          "mood":"FH"
       }
    },
    {
       "form":"talaðist",
       "grammarTag":"MM-FH-ÞT-2P-ET",
       "tags":{
          "person":"2P",
          "number":"ET",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"FH"
       }
    },
    {
       "form":"talist",
       "grammarTag":"MM-VH-NT-2P-ET",
       "tags":{
          "person":"2P",
          "number":"ET",
          "tense":"NT",
          "voice":"MM",
          "mood":"VH"
       }
    },
    {
       "form":"talaðist",
       "grammarTag":"MM-VH-ÞT-2P-ET",
       "tags":{
          "person":"2P",
          "number":"ET",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"VH"
       }
    },
    {
       "form":"talið",
       "grammarTag":"GM-BH-FT",
       "tags":{
          "number":"FT",
          "voice":"GM"
       }
    },
    {
       "form":"talaðir",
       "grammarTag":"LHÞT-SB-KK-NFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"KK"
       }
    },
    {
       "form":"talaða",
       "grammarTag":"LHÞT-SB-KK-ÞFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"KK"
       }
    },
    {
       "form":"töluðum",
       "grammarTag":"LHÞT-SB-KK-ÞGFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"KK"
       }
    },
    {
       "form":"talaðra",
       "grammarTag":"LHÞT-SB-KK-EFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"KK"
       }
    },
    {
       "form":"talaðar",
       "grammarTag":"LHÞT-SB-KVK-NFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"KVK"
       }
    },
    {
       "form":"talaðar",
       "grammarTag":"LHÞT-SB-KVK-ÞFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"KVK"
       }
    },
    {
       "form":"töluðum",
       "grammarTag":"LHÞT-SB-KVK-ÞGFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"KVK"
       }
    },
    {
       "form":"talaðra",
       "grammarTag":"LHÞT-SB-KVK-EFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"KVK"
       }
    },
    {
       "form":"töluð",
       "grammarTag":"LHÞT-SB-HK-NFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"HK"
       }
    },
    {
       "form":"töluð",
       "grammarTag":"LHÞT-SB-HK-ÞFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"HK"
       }
    },
    {
       "form":"töluðum",
       "grammarTag":"LHÞT-SB-HK-ÞGFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"HK"
       }
    },
    {
       "form":"talaðra",
       "grammarTag":"LHÞT-SB-HK-EFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"gr",
          "gender":"HK"
       }
    },
    {
       "form":"töluðu",
       "grammarTag":"LHÞT-VB-KK-NFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"KK"
       }
    },
    {
       "form":"töluðu",
       "grammarTag":"LHÞT-VB-KK-ÞFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"KK"
       }
    },
    {
       "form":"töluðu",
       "grammarTag":"LHÞT-VB-KK-ÞGFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"KK"
       }
    },
    {
       "form":"töluðu",
       "grammarTag":"LHÞT-VB-KK-EFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"KK"
       }
    },
    {
       "form":"töluðu",
       "grammarTag":"LHÞT-VB-KVK-NFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"KVK"
       }
    },
    {
       "form":"töluðu",
       "grammarTag":"LHÞT-VB-KVK-ÞFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"KVK"
       }
    },
    {
       "form":"töluðu",
       "grammarTag":"LHÞT-VB-KVK-ÞGFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"KVK"
       }
    },
    {
       "form":"töluðu",
       "grammarTag":"LHÞT-VB-KVK-EFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"KVK"
       }
    },
    {
       "form":"töluðu",
       "grammarTag":"LHÞT-VB-HK-NFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"HK"
       }
    },
    {
       "form":"töluðu",
       "grammarTag":"LHÞT-VB-HK-ÞFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"HK"
       }
    },
    {
       "form":"töluðu",
       "grammarTag":"LHÞT-VB-HK-ÞGFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"HK"
       }
    },
    {
       "form":"töluðu",
       "grammarTag":"LHÞT-VB-HK-EFFT",
       "tags":{
          "number":"FT",
          "tense":"ÞT",
          "past participal":"LHÞT",
          "article":"",
          "gender":"HK"
       }
    },
    {
       "form":"talast",
       "grammarTag":"OP-MM-FH-NT-2P-ET",
       "tags":{
          "person":"2P",
          "number":"ET",
          "tense":"NT",
          "voice":"MM",
          "mood":"FH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talaðist",
       "grammarTag":"OP-MM-FH-ÞT-2P-ET",
       "tags":{
          "person":"2P",
          "number":"ET",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"FH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talist",
       "grammarTag":"OP-MM-VH-NT-2P-ET",
       "tags":{
          "person":"2P",
          "number":"ET",
          "tense":"NT",
          "voice":"MM",
          "mood":"VH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talaðist",
       "grammarTag":"OP-MM-VH-ÞT-2P-ET",
       "tags":{
          "person":"2P",
          "number":"ET",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"VH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talar",
       "grammarTag":"GM-FH-NT-3P-ET",
       "tags":{
          "person":"3P",
          "number":"ET",
          "tense":"NT",
          "voice":"GM",
          "mood":"FH"
       }
    },
    {
       "form":"talaði",
       "grammarTag":"GM-FH-ÞT-3P-ET",
       "tags":{
          "person":"3P",
          "number":"ET",
          "tense":"ÞT",
          "voice":"GM",
          "mood":"FH"
       }
    },
    {
       "form":"tali",
       "grammarTag":"GM-VH-NT-3P-ET",
       "tags":{
          "person":"3P",
          "number":"ET",
          "tense":"NT",
          "voice":"GM",
          "mood":"VH"
       }
    },
    {
       "form":"talaði",
       "grammarTag":"GM-VH-ÞT-3P-ET",
       "tags":{
          "person":"3P",
          "number":"ET",
          "tense":"ÞT",
          "voice":"GM",
          "mood":"VH"
       }
    },
    {
       "form":"talast",
       "grammarTag":"MM-FH-NT-3P-ET",
       "tags":{
          "person":"3P",
          "number":"ET",
          "tense":"NT",
          "voice":"MM",
          "mood":"FH"
       }
    },
    {
       "form":"talaðist",
       "grammarTag":"MM-FH-ÞT-3P-ET",
       "tags":{
          "person":"3P",
          "number":"ET",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"FH"
       }
    },
    {
       "form":"talist",
       "grammarTag":"MM-VH-NT-3P-ET",
       "tags":{
          "person":"3P",
          "number":"ET",
          "tense":"NT",
          "voice":"MM",
          "mood":"VH"
       }
    },
    {
       "form":"talaðist",
       "grammarTag":"MM-VH-ÞT-3P-ET",
       "tags":{
          "person":"3P",
          "number":"ET",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"VH"
       }
    },
    {
       "form":"talast",
       "grammarTag":"OP-MM-FH-NT-3P-ET",
       "tags":{
          "person":"3P",
          "number":"ET",
          "tense":"NT",
          "voice":"MM",
          "mood":"FH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talaðist",
       "grammarTag":"OP-MM-FH-ÞT-3P-ET",
       "tags":{
          "person":"3P",
          "number":"ET",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"FH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talist",
       "grammarTag":"OP-MM-VH-NT-3P-ET",
       "tags":{
          "person":"3P",
          "number":"ET",
          "tense":"NT",
          "voice":"MM",
          "mood":"VH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talaðist",
       "grammarTag":"OP-MM-VH-ÞT-3P-ET",
       "tags":{
          "person":"3P",
          "number":"ET",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"VH",
          "impersonal":"OP"
       }
    },
    {
       "form":"tölum",
       "grammarTag":"GM-FH-NT-1P-FT",
       "tags":{
          "person":"1P",
          "number":"FT",
          "tense":"NT",
          "voice":"GM",
          "mood":"FH"
       }
    },
    {
       "form":"töluðum",
       "grammarTag":"GM-FH-ÞT-1P-FT",
       "tags":{
          "person":"1P",
          "number":"FT",
          "tense":"ÞT",
          "voice":"GM",
          "mood":"FH"
       }
    },
    {
       "form":"tölum",
       "grammarTag":"GM-VH-NT-1P-FT",
       "tags":{
          "person":"1P",
          "number":"FT",
          "tense":"NT",
          "voice":"GM",
          "mood":"VH"
       }
    },
    {
       "form":"töluðum",
       "grammarTag":"GM-VH-ÞT-1P-FT",
       "tags":{
          "person":"1P",
          "number":"FT",
          "tense":"ÞT",
          "voice":"GM",
          "mood":"VH"
       }
    },
    {
       "form":"tölumst",
       "grammarTag":"MM-FH-NT-1P-FT",
       "tags":{
          "person":"1P",
          "number":"FT",
          "tense":"NT",
          "voice":"MM",
          "mood":"FH"
       }
    },
    {
       "form":"töluðumst",
       "grammarTag":"MM-FH-ÞT-1P-FT",
       "tags":{
          "person":"1P",
          "number":"FT",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"FH"
       }
    },
    {
       "form":"tölumst",
       "grammarTag":"MM-VH-NT-1P-FT",
       "tags":{
          "person":"1P",
          "number":"FT",
          "tense":"NT",
          "voice":"MM",
          "mood":"VH"
       }
    },
    {
       "form":"töluðumst",
       "grammarTag":"MM-VH-ÞT-1P-FT",
       "tags":{
          "person":"1P",
          "number":"FT",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"VH"
       }
    },
    {
       "form":"talast",
       "grammarTag":"OP-MM-FH-NT-1P-FT",
       "tags":{
          "person":"1P",
          "number":"FT",
          "tense":"NT",
          "voice":"MM",
          "mood":"FH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talaðist",
       "grammarTag":"OP-MM-FH-ÞT-1P-FT",
       "tags":{
          "person":"1P",
          "number":"FT",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"FH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talist",
       "grammarTag":"OP-MM-VH-NT-1P-FT",
       "tags":{
          "person":"1P",
          "number":"FT",
          "tense":"NT",
          "voice":"MM",
          "mood":"VH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talaðist",
       "grammarTag":"OP-MM-VH-ÞT-1P-FT",
       "tags":{
          "person":"1P",
          "number":"FT",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"VH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talið",
       "grammarTag":"GM-FH-NT-2P-FT",
       "tags":{
          "person":"2P",
          "number":"FT",
          "tense":"NT",
          "voice":"GM",
          "mood":"FH"
       }
    },
    {
       "form":"töluðuð",
       "grammarTag":"GM-FH-ÞT-2P-FT",
       "tags":{
          "person":"2P",
          "number":"FT",
          "tense":"ÞT",
          "voice":"GM",
          "mood":"FH"
       }
    },
    {
       "form":"talið",
       "grammarTag":"GM-VH-NT-2P-FT",
       "tags":{
          "person":"2P",
          "number":"FT",
          "tense":"NT",
          "voice":"GM",
          "mood":"VH"
       }
    },
    {
       "form":"töluðuð",
       "grammarTag":"GM-VH-ÞT-2P-FT",
       "tags":{
          "person":"2P",
          "number":"FT",
          "tense":"ÞT",
          "voice":"GM",
          "mood":"VH"
       }
    },
    {
       "form":"talist",
       "grammarTag":"MM-FH-NT-2P-FT",
       "tags":{
          "person":"2P",
          "number":"FT",
          "tense":"NT",
          "voice":"MM",
          "mood":"FH"
       }
    },
    {
       "form":"töluðust",
       "grammarTag":"MM-FH-ÞT-2P-FT",
       "tags":{
          "person":"2P",
          "number":"FT",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"FH"
       }
    },
    {
       "form":"talist",
       "grammarTag":"MM-VH-NT-2P-FT",
       "tags":{
          "person":"2P",
          "number":"FT",
          "tense":"NT",
          "voice":"MM",
          "mood":"VH"
       }
    },
    {
       "form":"töluðust",
       "grammarTag":"MM-VH-ÞT-2P-FT",
       "tags":{
          "person":"2P",
          "number":"FT",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"VH"
       }
    },
    {
       "form":"talast",
       "grammarTag":"OP-MM-FH-NT-2P-FT",
       "tags":{
          "person":"2P",
          "number":"FT",
          "tense":"NT",
          "voice":"MM",
          "mood":"FH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talaðist",
       "grammarTag":"OP-MM-FH-ÞT-2P-FT",
       "tags":{
          "person":"2P",
          "number":"FT",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"FH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talist",
       "grammarTag":"OP-MM-VH-NT-2P-FT",
       "tags":{
          "person":"2P",
          "number":"FT",
          "tense":"NT",
          "voice":"MM",
          "mood":"VH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talaðist",
       "grammarTag":"OP-MM-VH-ÞT-2P-FT",
       "tags":{
          "person":"2P",
          "number":"FT",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"VH",
          "impersonal":"OP"
       }
    },
    {
       "form":"tala",
       "grammarTag":"GM-FH-NT-3P-FT",
       "tags":{
          "person":"3P",
          "number":"FT",
          "tense":"NT",
          "voice":"GM",
          "mood":"FH"
       }
    },
    {
       "form":"töluðu",
       "grammarTag":"GM-FH-ÞT-3P-FT",
       "tags":{
          "person":"3P",
          "number":"FT",
          "tense":"ÞT",
          "voice":"GM",
          "mood":"FH"
       }
    },
    {
       "form":"tali",
       "grammarTag":"GM-VH-NT-3P-FT",
       "tags":{
          "person":"3P",
          "number":"FT",
          "tense":"NT",
          "voice":"GM",
          "mood":"VH"
       }
    },
    {
       "form":"töluðu",
       "grammarTag":"GM-VH-ÞT-3P-FT",
       "tags":{
          "person":"3P",
          "number":"FT",
          "tense":"ÞT",
          "voice":"GM",
          "mood":"VH"
       }
    },
    {
       "form":"talast",
       "grammarTag":"MM-FH-NT-3P-FT",
       "tags":{
          "person":"3P",
          "number":"FT",
          "tense":"NT",
          "voice":"MM",
          "mood":"FH"
       }
    },
    {
       "form":"töluðust",
       "grammarTag":"MM-FH-ÞT-3P-FT",
       "tags":{
          "person":"3P",
          "number":"FT",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"FH"
       }
    },
    {
       "form":"talist",
       "grammarTag":"MM-VH-NT-3P-FT",
       "tags":{
          "person":"3P",
          "number":"FT",
          "tense":"NT",
          "voice":"MM",
          "mood":"VH"
       }
    },
    {
       "form":"töluðust",
       "grammarTag":"MM-VH-ÞT-3P-FT",
       "tags":{
          "person":"3P",
          "number":"FT",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"VH"
       }
    },
    {
       "form":"talast",
       "grammarTag":"OP-MM-FH-NT-3P-FT",
       "tags":{
          "person":"3P",
          "number":"FT",
          "tense":"NT",
          "voice":"MM",
          "mood":"FH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talaðist",
       "grammarTag":"OP-MM-FH-ÞT-3P-FT",
       "tags":{
          "person":"3P",
          "number":"FT",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"FH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talist",
       "grammarTag":"OP-MM-VH-NT-3P-FT",
       "tags":{
          "person":"3P",
          "number":"FT",
          "tense":"NT",
          "voice":"MM",
          "mood":"VH",
          "impersonal":"OP"
       }
    },
    {
       "form":"talaðist",
       "grammarTag":"OP-MM-VH-ÞT-3P-FT",
       "tags":{
          "person":"3P",
          "number":"FT",
          "tense":"ÞT",
          "voice":"MM",
          "mood":"VH",
          "impersonal":"OP"
       }
    },
    {
       "form":"tala",
       "grammarTag":"GM-NH",
       "tags":{
          "voice":"GM"
       }
    },
    {
       "form":"talast",
       "grammarTag":"MM-NH",
       "tags":{
          "voice":"MM"
       }
    },
    {
       "form":"tala",
       "grammarTag":"GM-BH-ST",
       "tags":{
          "voice":"GM"
       }
    },
    {
       "form":"talandi",
       "grammarTag":"LH-NT",
       "tags":{
          "tense":"NT"
       }
    },
    {
       "form":"talað",
       "grammarTag":"GM-SAGNB",
       "tags":{
          "voice":"GM"
       }
    },
    {
       "form":"talast",
       "grammarTag":"MM-SAGNB",
       "tags":{
          "voice":"MM"
       }
    }
  ]
}]]
